#!/bin/bash
#
# chkconfig: 35 90 12
# description: gitlab-puppet-webhook
#
# Load base functions
. /etc/init.d/functions

## YOU MUST UPDATE THE PATH TO THE SCRIPT
DAEMONPATH=/opt/bin/
#### Stop editing ####
DAEMON=gitlab-puppet-webhook
LOCKFILE=/var/lock/subsys/gitlab-puppet-webhook
PIDFILE=${DAEMONPATH}gitlab-puppet-webhook.pid

# Start the Service
start() {
	echo -n "Starting Gitlab Puppet Webhook: "
	`${DAEMON}`
	## Create a lock file ##
	touch ${LOCKFILE}
	success $"Gitlab Puppet Webhook startup"
	echo
}
# Stop the Service
stop() {
	echo -n "Stopping Gitlab Puppet Webhook: "
	killproc -p $PIDFILE $DAEMON
	## Delete the lock file ##
	rm -f ${LOCKFILE}
	echo
}
status() {
	if [ -f ${PIDFILE}]; then
		PID=`cat ${PIDFILE}`
		if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
			printf "%s\n" "Process dead but pidfile exists"
		else
			echo "Running"
		fi
	else
		printf "%s\n" "Service not running"
	fi
}

### The logic bits ###
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload|condrestart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
esac
exit 0
